import prisma from '@/lib/prisma';
import { TaskPriority, TaskProgress } from '@prisma/client'; // Enums generated by Prisma

interface TaskI {
  projectId: number;
  name: string;
  priority: TaskPriority;
  progress: TaskProgress;
}

export async function createTask(data: TaskI) {
  try {
    const project = await prisma.task.create({
      data: {
        projectId: data.projectId,
        name: data.name,
        priority: data.priority,
        progress: data.progress
      }
    });
    return { project };
  } catch (error: unknown) {
    if (error instanceof Error) {
      return { error: error.message };
    } else {
      return { error: 'Failed to create the task.' };
    }
  }
}
